highlighter: rouge
markdown: kramdown
repository: https://github.com/stepcode/stepcode
#help_url: https://github.com/jekyll/jekyll-help

collections:
  docs:
    output: true

kramdown:
  toc_levels: "2"
